#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{        0, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x2d3385d3, __VMLINUX_SYMBOL_STR(system_wq) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xc9af9ea0, __VMLINUX_SYMBOL_STR(rds_page_copy_user) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0xc897c382, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0xf5893abf, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0x298bf7a5, __VMLINUX_SYMBOL_STR(rds_trans_register) },
	{ 0x73aac73d, __VMLINUX_SYMBOL_STR(rds_message_populate_header) },
	{ 0xb5058f9d, __VMLINUX_SYMBOL_STR(rds_message_put) },
	{ 0xd6ee688f, __VMLINUX_SYMBOL_STR(vmalloc) },
	{ 0xb6b46a7c, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x2fdab68f, __VMLINUX_SYMBOL_STR(ib_dealloc_pd) },
	{ 0x1974d97b, __VMLINUX_SYMBOL_STR(ib_alloc_fast_reg_mr) },
	{ 0xc7a1840e, __VMLINUX_SYMBOL_STR(llist_add_batch) },
	{ 0x10a15f1e, __VMLINUX_SYMBOL_STR(rds_connect_complete) },
	{ 0x7505d413, __VMLINUX_SYMBOL_STR(rds_str_array) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0xdbdb84eb, __VMLINUX_SYMBOL_STR(unregister_net_sysctl_table) },
	{ 0x17795916, __VMLINUX_SYMBOL_STR(cpu_online_mask) },
	{ 0xd838764a, __VMLINUX_SYMBOL_STR(rds_message_unmapped) },
	{ 0xd067fc5c, __VMLINUX_SYMBOL_STR(proc_dointvec) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x6b06fdce, __VMLINUX_SYMBOL_STR(delayed_work_timer_fn) },
	{ 0x50cbe7b3, __VMLINUX_SYMBOL_STR(rds_stats) },
	{ 0xc8f4826d, __VMLINUX_SYMBOL_STR(rdma_accept) },
	{ 0xe4cbc5df, __VMLINUX_SYMBOL_STR(rds_conn_create) },
	{ 0x7559e594, __VMLINUX_SYMBOL_STR(ib_free_fast_reg_page_list) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0xd7edd9, __VMLINUX_SYMBOL_STR(x86_dma_fallback_dev) },
	{ 0x949f7342, __VMLINUX_SYMBOL_STR(__alloc_percpu) },
	{ 0xe6ba4f07, __VMLINUX_SYMBOL_STR(rdma_destroy_id) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x797c8fa9, __VMLINUX_SYMBOL_STR(cancel_delayed_work_sync) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x4c04ec1, __VMLINUX_SYMBOL_STR(rds_recv_incoming) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x40c7247c, __VMLINUX_SYMBOL_STR(si_meminfo) },
	{ 0x9181602d, __VMLINUX_SYMBOL_STR(set_page_dirty) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xc9ec4e21, __VMLINUX_SYMBOL_STR(free_percpu) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0xbbbad606, __VMLINUX_SYMBOL_STR(ib_modify_qp) },
	{ 0xbecbf4d3, __VMLINUX_SYMBOL_STR(mutex_trylock) },
	{ 0xee9cafdd, __VMLINUX_SYMBOL_STR(rds_inc_init) },
	{ 0x57a6ccd0, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0xcddc09bd, __VMLINUX_SYMBOL_STR(rdma_connect) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0x1e491a04, __VMLINUX_SYMBOL_STR(ib_unmap_fmr) },
	{ 0x877e422f, __VMLINUX_SYMBOL_STR(ib_alloc_pd) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xc5b503a8, __VMLINUX_SYMBOL_STR(ib_get_dma_mr) },
	{ 0xd1c42aa1, __VMLINUX_SYMBOL_STR(ib_query_device) },
	{ 0x5d9fa7a3, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3b4fc0fc, __VMLINUX_SYMBOL_STR(rds_page_remainder_alloc) },
	{ 0xad020a32, __VMLINUX_SYMBOL_STR(rdma_destroy_qp) },
	{ 0x4d57cda, __VMLINUX_SYMBOL_STR(rds_info_register_func) },
	{ 0x99e4b8b2, __VMLINUX_SYMBOL_STR(rdma_listen) },
	{ 0x85625697, __VMLINUX_SYMBOL_STR(ib_get_client_data) },
	{ 0xfaef0ed, __VMLINUX_SYMBOL_STR(__tasklet_schedule) },
	{ 0x9725b589, __VMLINUX_SYMBOL_STR(proc_doulongvec_minmax) },
	{ 0x3d0e31ba, __VMLINUX_SYMBOL_STR(rdma_notify) },
	{ 0x3101936e, __VMLINUX_SYMBOL_STR(rds_message_add_extension) },
	{ 0xbf8ba54a, __VMLINUX_SYMBOL_STR(vprintk) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xefeb91dc, __VMLINUX_SYMBOL_STR(rds_inc_put) },
	{ 0x7bc62829, __VMLINUX_SYMBOL_STR(rds_stats_info_copy) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x82d31360, __VMLINUX_SYMBOL_STR(dev_get_by_index) },
	{ 0x9545af6d, __VMLINUX_SYMBOL_STR(tasklet_init) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0x414982f6, __VMLINUX_SYMBOL_STR(rds_send_drop_acked) },
	{ 0x724f0b57, __VMLINUX_SYMBOL_STR(init_net) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x1139206d, __VMLINUX_SYMBOL_STR(ib_set_client_data) },
	{ 0x3d769dfc, __VMLINUX_SYMBOL_STR(__get_page_tail) },
	{ 0x5a643b1f, __VMLINUX_SYMBOL_STR(rdma_create_id) },
	{ 0x42160169, __VMLINUX_SYMBOL_STR(flush_workqueue) },
	{ 0xf910f34, __VMLINUX_SYMBOL_STR(ib_destroy_cq) },
	{ 0xe284bf89, __VMLINUX_SYMBOL_STR(rds_rdma_send_complete) },
	{ 0x82072614, __VMLINUX_SYMBOL_STR(tasklet_kill) },
	{ 0xde9be17, __VMLINUX_SYMBOL_STR(rds_conn_destroy) },
	{ 0xda440ed3, __VMLINUX_SYMBOL_STR(rdma_create_qp) },
	{ 0x8c2bcc53, __VMLINUX_SYMBOL_STR(ib_register_client) },
	{ 0x97efac0c, __VMLINUX_SYMBOL_STR(rdma_bind_addr) },
	{ 0xfa070666, __VMLINUX_SYMBOL_STR(rds_conn_connect_if_down) },
	{ 0xae2661a2, __VMLINUX_SYMBOL_STR(rds_atomic_send_complete) },
	{ 0xb9d025c9, __VMLINUX_SYMBOL_STR(llist_del_first) },
	{ 0x368548fa, __VMLINUX_SYMBOL_STR(rdma_resolve_route) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xea248cef, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x232bc1bf, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_node_trace) },
	{ 0x19ed6bfa, __VMLINUX_SYMBOL_STR(ib_dealloc_fmr) },
	{ 0xeeec26a7, __VMLINUX_SYMBOL_STR(queue_delayed_work_on) },
	{ 0x73032782, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0xa467af, __VMLINUX_SYMBOL_STR(rds_wq) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x79a38e61, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x43261dca, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x2c5c5514, __VMLINUX_SYMBOL_STR(rds_message_add_rdma_dest_extension) },
	{ 0x60241635, __VMLINUX_SYMBOL_STR(rds_for_each_conn_info) },
	{ 0x1e579dc5, __VMLINUX_SYMBOL_STR(__list_add_rcu) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0xc013590b, __VMLINUX_SYMBOL_STR(rds_send_get_message) },
	{ 0x8382c933, __VMLINUX_SYMBOL_STR(rdma_disconnect) },
	{ 0x28281e54, __VMLINUX_SYMBOL_STR(ib_alloc_fmr) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb19a5453, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0xf5d5be88, __VMLINUX_SYMBOL_STR(rdma_reject) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd976ad5e, __VMLINUX_SYMBOL_STR(ib_dereg_mr) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xc5c4941e, __VMLINUX_SYMBOL_STR(rds_info_deregister_func) },
	{ 0x5c8b5ce8, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0xda03a15b, __VMLINUX_SYMBOL_STR(rds_trans_unregister) },
	{ 0xb614c9ca, __VMLINUX_SYMBOL_STR(rdma_resolve_addr) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x312ca88d, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0x649e7d, __VMLINUX_SYMBOL_STR(ib_alloc_fast_reg_page_list) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1dcd214, __VMLINUX_SYMBOL_STR(ib_create_cq) },
	{ 0x55f5019b, __VMLINUX_SYMBOL_STR(__kmalloc_node) },
	{ 0x2e0d2f7f, __VMLINUX_SYMBOL_STR(queue_work_on) },
	{ 0x9e0c711d, __VMLINUX_SYMBOL_STR(vzalloc_node) },
	{ 0xf0e4d7bc, __VMLINUX_SYMBOL_STR(register_net_sysctl) },
	{ 0x791666c2, __VMLINUX_SYMBOL_STR(rds_message_addref) },
	{ 0xe4793ba6, __VMLINUX_SYMBOL_STR(ib_unregister_client) },
	{ 0x74f94f95, __VMLINUX_SYMBOL_STR(dma_ops) },
	{ 0x63ddd1fd, __VMLINUX_SYMBOL_STR(rds_conn_drop) },
	{ 0xbef4936, __VMLINUX_SYMBOL_STR(rds_cong_map_updated) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=rds,ib_core,rdma_cm";


MODULE_INFO(srcversion, "4791272FDF35D7EF8B26620");
