#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xae5f1b70, __VMLINUX_SYMBOL_STR(ata_std_prereset) },
	{ 0x2f1b79ef, __VMLINUX_SYMBOL_STR(ata_port_wait_eh) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x51ce7b2f, __VMLINUX_SYMBOL_STR(sas_remove_children) },
	{ 0xdc6b8a6, __VMLINUX_SYMBOL_STR(ata_sas_port_async_resume) },
	{ 0xe88a2324, __VMLINUX_SYMBOL_STR(sas_release_transport) },
	{ 0x8ce068bb, __VMLINUX_SYMBOL_STR(blk_queue_free_tags) },
	{ 0x36938bd6, __VMLINUX_SYMBOL_STR(scsi_track_queue_full) },
	{ 0xc996d097, __VMLINUX_SYMBOL_STR(del_timer) },
	{ 0x43e342d, __VMLINUX_SYMBOL_STR(blk_abort_request) },
	{ 0x56fef0ed, __VMLINUX_SYMBOL_STR(scsi_block_requests) },
	{ 0xa464bd0a, __VMLINUX_SYMBOL_STR(ata_std_sched_eh) },
	{ 0xc8b57c27, __VMLINUX_SYMBOL_STR(autoremove_wake_function) },
	{ 0x431c01db, __VMLINUX_SYMBOL_STR(sas_port_free) },
	{ 0x28c17900, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0xbdf0c473, __VMLINUX_SYMBOL_STR(sas_phy_add) },
	{ 0xb0a37bbe, __VMLINUX_SYMBOL_STR(scsi_unblock_requests) },
	{ 0xf4f73208, __VMLINUX_SYMBOL_STR(ata_sas_slave_configure) },
	{ 0x1b0d2a6e, __VMLINUX_SYMBOL_STR(ata_scsi_cmd_error_handler) },
	{ 0xfb1e49d6, __VMLINUX_SYMBOL_STR(sas_port_add_phy) },
	{ 0x3fec048f, __VMLINUX_SYMBOL_STR(sg_next) },
	{ 0x85c891c9, __VMLINUX_SYMBOL_STR(sas_rphy_free) },
	{ 0x593a99b, __VMLINUX_SYMBOL_STR(init_timer_key) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xbf4657, __VMLINUX_SYMBOL_STR(sas_port_delete_phy) },
	{ 0xd9119b9d, __VMLINUX_SYMBOL_STR(sas_rphy_add) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x4e3619a0, __VMLINUX_SYMBOL_STR(ata_sas_port_init) },
	{ 0xd5b2e96, __VMLINUX_SYMBOL_STR(scsi_adjust_queue_depth) },
	{ 0xb550b14e, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x214c1110, __VMLINUX_SYMBOL_STR(sas_port_delete) },
	{ 0x2a620e89, __VMLINUX_SYMBOL_STR(ata_sas_async_probe) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x78598cd6, __VMLINUX_SYMBOL_STR(sas_attach_transport) },
	{ 0x6d0aba34, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x2b137529, __VMLINUX_SYMBOL_STR(scsi_is_host_device) },
	{ 0xd95c234c, __VMLINUX_SYMBOL_STR(sas_rphy_delete) },
	{ 0x26f444d3, __VMLINUX_SYMBOL_STR(ata_sas_port_stop) },
	{ 0x60fa839e, __VMLINUX_SYMBOL_STR(scsi_queue_work) },
	{ 0xaa6244f0, __VMLINUX_SYMBOL_STR(sas_expander_alloc) },
	{ 0x11089ac7, __VMLINUX_SYMBOL_STR(_ctype) },
	{ 0x8f64aa4, __VMLINUX_SYMBOL_STR(_raw_spin_unlock_irqrestore) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0xee2bfd79, __VMLINUX_SYMBOL_STR(sas_read_port_mode_page) },
	{ 0xfa2aa703, __VMLINUX_SYMBOL_STR(mutex_lock_interruptible) },
	{ 0xe2c3539b, __VMLINUX_SYMBOL_STR(sas_end_device_alloc) },
	{ 0x5d9fa7a3, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xbfb3f5f4, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x20fc41b2, __VMLINUX_SYMBOL_STR(ata_std_error_handler) },
	{ 0x6c34999b, __VMLINUX_SYMBOL_STR(ata_scsi_port_error_handler) },
	{ 0x9acf8479, __VMLINUX_SYMBOL_STR(ata_sas_port_start) },
	{ 0x5a16a9cf, __VMLINUX_SYMBOL_STR(ata_std_qc_defer) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0xd571552d, __VMLINUX_SYMBOL_STR(sas_port_mark_backlink) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xc268565b, __VMLINUX_SYMBOL_STR(sas_port_add) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xbe2c0274, __VMLINUX_SYMBOL_STR(add_timer) },
	{ 0xf811e69d, __VMLINUX_SYMBOL_STR(scsi_eh_flush_done_q) },
	{ 0x47a42c60, __VMLINUX_SYMBOL_STR(ata_port_schedule_eh) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x9596e6b6, __VMLINUX_SYMBOL_STR(ata_sas_port_alloc) },
	{ 0x35eb7c48, __VMLINUX_SYMBOL_STR(ata_noop_qc_prep) },
	{ 0xefa39df7, __VMLINUX_SYMBOL_STR(scsi_eh_finish_cmd) },
	{ 0x9506ec3c, __VMLINUX_SYMBOL_STR(sas_phy_free) },
	{ 0xe86cca58, __VMLINUX_SYMBOL_STR(_dev_info) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x4aff7de5, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x3bd1b1f6, __VMLINUX_SYMBOL_STR(msecs_to_jiffies) },
	{ 0x6cd21997, __VMLINUX_SYMBOL_STR(ata_tf_to_fis) },
	{        0, __VMLINUX_SYMBOL_STR(schedule_timeout) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x43261dca, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irq) },
	{ 0x62e67fbd, __VMLINUX_SYMBOL_STR(sas_phy_alloc) },
	{ 0x374e0d31, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x8769d09, __VMLINUX_SYMBOL_STR(ata_wait_after_reset) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x9327f5ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock_irqsave) },
	{ 0x4994dbfa, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x26c90ea4, __VMLINUX_SYMBOL_STR(scsi_eh_get_sense) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0xea10212a, __VMLINUX_SYMBOL_STR(int_to_scsilun) },
	{ 0xb6244511, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xeac791d4, __VMLINUX_SYMBOL_STR(blk_queue_init_tags) },
	{ 0x133c3884, __VMLINUX_SYMBOL_STR(sas_port_get_phy) },
	{ 0x9c55cec, __VMLINUX_SYMBOL_STR(schedule_timeout_interruptible) },
	{ 0xbd55ebc1, __VMLINUX_SYMBOL_STR(scsi_eh_ready_devs) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0x9304b6, __VMLINUX_SYMBOL_STR(ata_tf_from_fis) },
	{ 0x5c8b5ce8, __VMLINUX_SYMBOL_STR(prepare_to_wait) },
	{ 0x9f61d949, __VMLINUX_SYMBOL_STR(sas_port_alloc) },
	{ 0xbd546902, __VMLINUX_SYMBOL_STR(ata_host_init) },
	{ 0x3e017515, __VMLINUX_SYMBOL_STR(request_firmware) },
	{ 0x53a79514, __VMLINUX_SYMBOL_STR(scsi_schedule_eh) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x93b54a87, __VMLINUX_SYMBOL_STR(dev_warn) },
	{ 0xe75784de, __VMLINUX_SYMBOL_STR(ata_sas_port_async_suspend) },
	{ 0xce7b09d, __VMLINUX_SYMBOL_STR(ata_std_postreset) },
	{ 0x85899930, __VMLINUX_SYMBOL_STR(sas_rphy_unlink) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x564bcfe, __VMLINUX_SYMBOL_STR(ata_sas_queuecmd) },
	{ 0x12fb4583, __VMLINUX_SYMBOL_STR(ata_sas_port_destroy) },
	{ 0xa38602cd, __VMLINUX_SYMBOL_STR(drain_workqueue) },
	{ 0x24b2ab73, __VMLINUX_SYMBOL_STR(sas_rphy_remove) },
	{ 0xf82fecbd, __VMLINUX_SYMBOL_STR(release_firmware) },
	{ 0x42d3835e, __VMLINUX_SYMBOL_STR(ata_sas_scsi_ioctl) },
	{ 0xd453da9b, __VMLINUX_SYMBOL_STR(__ata_change_queue_depth) },
	{ 0x6de0cc5c, __VMLINUX_SYMBOL_STR(ata_qc_complete) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=scsi_transport_sas";


MODULE_INFO(srcversion, "D9056442C5D67E283BCD984");
