#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x97321d0e, __VMLINUX_SYMBOL_STR(drop_nlink) },
	{ 0xc868828b, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0xf5893abf, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xb558172, __VMLINUX_SYMBOL_STR(__bread) },
	{ 0x8c47b357, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0x24de2513, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0xbafbf0b1, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xf2966369, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x3a53aea2, __VMLINUX_SYMBOL_STR(inode_permission) },
	{ 0x6d356209, __VMLINUX_SYMBOL_STR(crc_itu_t) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0xb10ea1e5, __VMLINUX_SYMBOL_STR(simple_write_end) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x34184afe, __VMLINUX_SYMBOL_STR(current_kernel_time) },
	{ 0x8fc44b1d, __VMLINUX_SYMBOL_STR(block_write_begin) },
	{ 0xc35a6a00, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0x7790b8d8, __VMLINUX_SYMBOL_STR(is_bad_inode) },
	{ 0x64fb24e9, __VMLINUX_SYMBOL_STR(generic_file_open) },
	{ 0x9b0c8220, __VMLINUX_SYMBOL_STR(_raw_read_lock) },
	{ 0xb1cf3c4e, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0x58f2bec7, __VMLINUX_SYMBOL_STR(ll_rw_block) },
	{ 0x4b950d81, __VMLINUX_SYMBOL_STR(__lock_buffer) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0x865e35da, __VMLINUX_SYMBOL_STR(generic_file_aio_read) },
	{ 0xa05f372e, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x9d23c1ba, __VMLINUX_SYMBOL_STR(inc_nlink) },
	{ 0xdbee9a05, __VMLINUX_SYMBOL_STR(__generic_file_aio_write) },
	{ 0x3f2a0f29, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xf086ecb2, __VMLINUX_SYMBOL_STR(mount_bdev) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xd72edc5d, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x999e8297, __VMLINUX_SYMBOL_STR(vfree) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0xfc9f8c25, __VMLINUX_SYMBOL_STR(unlock_buffer) },
	{ 0x6fda9a09, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x57a6ccd0, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x28124e6f, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xc671e369, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x1c51fc5d, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x39c4d998, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xb8e7ce2c, __VMLINUX_SYMBOL_STR(__put_user_8) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xdaf23bd8, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0x8bf9349d, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{        0, __VMLINUX_SYMBOL_STR(inode_add_bytes) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{        0, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x5d9fa7a3, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xe90a0714, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xe6d47fbd, __VMLINUX_SYMBOL_STR(find_or_create_page) },
	{ 0x1e1aa4a2, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0x4096bf3b, __VMLINUX_SYMBOL_STR(from_kgid) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xad4edda, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x7d5c20a8, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0x13a1a61a, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x6afebb3c, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0xa8288a65, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x5994e990, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x154c8b30, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xda96b76d, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0xa4fc6e2a, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x8d930007, __VMLINUX_SYMBOL_STR(page_follow_link_light) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x78c2ba27, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x40a9b349, __VMLINUX_SYMBOL_STR(vzalloc) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0x525912ad, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x84037d01, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0xf219b6f1, __VMLINUX_SYMBOL_STR(inode_sub_bytes) },
	{ 0xdaf2fd26, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0x751d3c2d, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0x6d334118, __VMLINUX_SYMBOL_STR(__get_user_8) },
	{ 0x5c058c00, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{        0, __VMLINUX_SYMBOL_STR(do_sync_read) },
	{ 0xd5ddde83, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0xd73c65d6, __VMLINUX_SYMBOL_STR(kill_block_super) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x933c234d, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{        0, __VMLINUX_SYMBOL_STR(d_tmpfile) },
	{ 0xba797153, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0xd7317d, __VMLINUX_SYMBOL_STR(iput) },
	{ 0xae145ca4, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x861af486, __VMLINUX_SYMBOL_STR(do_sync_write) },
	{ 0x3c9fa68, __VMLINUX_SYMBOL_STR(ihold) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x943608cc, __VMLINUX_SYMBOL_STR(load_nls_default) },
	{ 0xbfe59182, __VMLINUX_SYMBOL_STR(d_splice_alias) },
	{ 0x21ae354d, __VMLINUX_SYMBOL_STR(block_truncate_page) },
	{ 0x184c0cf8, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0xbf955900, __VMLINUX_SYMBOL_STR(generic_readlink) },
	{ 0x312ca88d, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xbb79dce5, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x904741e7, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x4cbbd171, __VMLINUX_SYMBOL_STR(__bitmap_weight) },
	{ 0xcc4dda2d, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0x9be786f, __VMLINUX_SYMBOL_STR(ioctl_by_bdev) },
	{ 0x7b22ce17, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xbd5ebbe5, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0x5beec9af, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xd2c50e95, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x59b5d5f5, __VMLINUX_SYMBOL_STR(__getblk) },
	{ 0x267ef61f, __VMLINUX_SYMBOL_STR(grab_cache_page_write_begin) },
	{ 0x1bac5398, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x6308b045, __VMLINUX_SYMBOL_STR(page_put_link) },
	{ 0x1a7ce1b9, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x2a6e6109, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x66786927, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0x6f2bc228, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0x2c9b5907, __VMLINUX_SYMBOL_STR(iget_locked) },
	{ 0xf812cff6, __VMLINUX_SYMBOL_STR(memscan) },
	{        0, __VMLINUX_SYMBOL_STR(vfs_fsync_range) },
	{ 0xb3015691, __VMLINUX_SYMBOL_STR(inode_init_owner) },
	{ 0x8dc7f424, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=crc-itu-t";


MODULE_INFO(srcversion, "53309F1753D6B263CB27A12");
