#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xd05288a5, __VMLINUX_SYMBOL_STR(blkdev_issue_discard) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0x405c1144, __VMLINUX_SYMBOL_STR(get_seconds) },
	{ 0x7129e5f8, __VMLINUX_SYMBOL_STR(hex_asc) },
	{ 0xf37509e0, __VMLINUX_SYMBOL_STR(sb_min_blocksize) },
	{ 0xc868828b, __VMLINUX_SYMBOL_STR(mark_buffer_dirty_inode) },
	{ 0xf5893abf, __VMLINUX_SYMBOL_STR(up_read) },
	{ 0xb558172, __VMLINUX_SYMBOL_STR(__bread) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x8c47b357, __VMLINUX_SYMBOL_STR(unload_nls) },
	{ 0xbafbf0b1, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xf2966369, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x27f15ec9, __VMLINUX_SYMBOL_STR(from_kuid_munged) },
	{ 0x815b5dd4, __VMLINUX_SYMBOL_STR(match_octal) },
	{ 0x64999478, __VMLINUX_SYMBOL_STR(congestion_wait) },
	{ 0x92a9c60c, __VMLINUX_SYMBOL_STR(time_to_tm) },
	{ 0x2d837248, __VMLINUX_SYMBOL_STR(generic_fh_to_parent) },
	{ 0xc35a6a00, __VMLINUX_SYMBOL_STR(seq_puts) },
	{ 0xacf4d843, __VMLINUX_SYMBOL_STR(match_strdup) },
	{ 0xcae232b, __VMLINUX_SYMBOL_STR(utf16s_to_utf8s) },
	{ 0x865e35da, __VMLINUX_SYMBOL_STR(generic_file_aio_read) },
	{ 0xa05f372e, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x6729d3df, __VMLINUX_SYMBOL_STR(__get_user_4) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x3f2a0f29, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0xf137d372, __VMLINUX_SYMBOL_STR(names_cachep) },
	{ 0x2d067075, __VMLINUX_SYMBOL_STR(filemap_fdatawait_range) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xd72edc5d, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x365d226, __VMLINUX_SYMBOL_STR(igrab) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xe0ff5a4c, __VMLINUX_SYMBOL_STR(generic_file_aio_write) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6fda9a09, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0x57a6ccd0, __VMLINUX_SYMBOL_STR(down_read) },
	{ 0x16a2a1ba, __VMLINUX_SYMBOL_STR(from_kgid_munged) },
	{ 0x28124e6f, __VMLINUX_SYMBOL_STR(make_kgid) },
	{ 0xc671e369, __VMLINUX_SYMBOL_STR(_copy_to_user) },
	{ 0x1c51fc5d, __VMLINUX_SYMBOL_STR(__insert_inode_hash) },
	{ 0x39c4d998, __VMLINUX_SYMBOL_STR(mpage_readpages) },
	{ 0xb8e7ce2c, __VMLINUX_SYMBOL_STR(__put_user_8) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x8bf9349d, __VMLINUX_SYMBOL_STR(mpage_readpage) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{        0, __VMLINUX_SYMBOL_STR(current_fs_time) },
	{ 0x5d9fa7a3, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xe90a0714, __VMLINUX_SYMBOL_STR(d_obtain_alias) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xd430acf6, __VMLINUX_SYMBOL_STR(write_inode_now) },
	{ 0x7c1372e8, __VMLINUX_SYMBOL_STR(panic) },
	{ 0x1e1aa4a2, __VMLINUX_SYMBOL_STR(mpage_writepages) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xc3aaf0a9, __VMLINUX_SYMBOL_STR(__put_user_1) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xad4edda, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x7d5c20a8, __VMLINUX_SYMBOL_STR(__wait_on_buffer) },
	{ 0x6afebb3c, __VMLINUX_SYMBOL_STR(setattr_copy) },
	{ 0xa8288a65, __VMLINUX_SYMBOL_STR(sync_dirty_buffer) },
	{ 0x5994e990, __VMLINUX_SYMBOL_STR(truncate_pagecache) },
	{ 0x4e3567f7, __VMLINUX_SYMBOL_STR(match_int) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0xda96b76d, __VMLINUX_SYMBOL_STR(__brelse) },
	{ 0xfe5d4bb2, __VMLINUX_SYMBOL_STR(sys_tz) },
	{ 0xf38905bc, __VMLINUX_SYMBOL_STR(__fsnotify_parent) },
	{ 0xa4fc6e2a, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0xc354f251, __VMLINUX_SYMBOL_STR(mnt_drop_write_file) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0x78c2ba27, __VMLINUX_SYMBOL_STR(invalidate_inode_buffers) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x97a8c94d, __VMLINUX_SYMBOL_STR(ilookup) },
	{ 0xb2fd5ceb, __VMLINUX_SYMBOL_STR(__put_user_4) },
	{ 0x5b0b25f5, __VMLINUX_SYMBOL_STR(sync_mapping_buffers) },
	{ 0x525912ad, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x84037d01, __VMLINUX_SYMBOL_STR(block_write_full_page) },
	{ 0xdaf2fd26, __VMLINUX_SYMBOL_STR(make_kuid) },
	{ 0xe50b50e5, __VMLINUX_SYMBOL_STR(generic_cont_expand_simple) },
	{ 0x751d3c2d, __VMLINUX_SYMBOL_STR(load_nls) },
	{ 0x79a38e61, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x5c058c00, __VMLINUX_SYMBOL_STR(generic_write_end) },
	{ 0x3f73fd6e, __VMLINUX_SYMBOL_STR(__breadahead) },
	{        0, __VMLINUX_SYMBOL_STR(do_sync_read) },
	{ 0x8566339b, __VMLINUX_SYMBOL_STR(mnt_want_write_file) },
	{        0, __VMLINUX_SYMBOL_STR(in_group_p) },
	{ 0x5e95b1cd, __VMLINUX_SYMBOL_STR(current_umask) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x933c234d, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x3efcb4bb, __VMLINUX_SYMBOL_STR(sync_inode_metadata) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xd7317d, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x3f0fc23f, __VMLINUX_SYMBOL_STR(cont_write_begin) },
	{ 0xae145ca4, __VMLINUX_SYMBOL_STR(generic_file_fsync) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x7a39a713, __VMLINUX_SYMBOL_STR(iunique) },
	{ 0xf0b4db40, __VMLINUX_SYMBOL_STR(inode_dio_wait) },
	{ 0x861af486, __VMLINUX_SYMBOL_STR(do_sync_write) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x77c2428a, __VMLINUX_SYMBOL_STR(fsnotify) },
	{ 0x2f855abe, __VMLINUX_SYMBOL_STR(write_dirty_buffer) },
	{ 0x184c0cf8, __VMLINUX_SYMBOL_STR(sb_set_blocksize) },
	{ 0x5185f2, __VMLINUX_SYMBOL_STR(__bforget) },
	{ 0xbb79dce5, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x904741e7, __VMLINUX_SYMBOL_STR(__blockdev_direct_IO) },
	{ 0x5a4896a8, __VMLINUX_SYMBOL_STR(__put_user_2) },
	{ 0x6b9c24a2, __VMLINUX_SYMBOL_STR(inode_needs_sync) },
	{ 0xae5c7023, __VMLINUX_SYMBOL_STR(filemap_fdatawrite_range) },
	{ 0x76abbdac, __VMLINUX_SYMBOL_STR(__find_get_block) },
	{ 0x1115755a, __VMLINUX_SYMBOL_STR(security_inode_setattr) },
	{ 0xcc4dda2d, __VMLINUX_SYMBOL_STR(mark_buffer_dirty) },
	{ 0x5beec9af, __VMLINUX_SYMBOL_STR(new_inode) },
	{ 0xd2c50e95, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0x59b5d5f5, __VMLINUX_SYMBOL_STR(__getblk) },
	{ 0x8de50a71, __VMLINUX_SYMBOL_STR(generic_fh_to_dentry) },
	{ 0x1bac5398, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x2a6e6109, __VMLINUX_SYMBOL_STR(__init_rwsem) },
	{ 0x89caaacd, __VMLINUX_SYMBOL_STR(filemap_flush) },
	{ 0x66786927, __VMLINUX_SYMBOL_STR(generic_block_bmap) },
	{ 0x4c1b0f4e, __VMLINUX_SYMBOL_STR(generic_fillattr) },
	{ 0xf1fa80de, __VMLINUX_SYMBOL_STR(filemap_fdatawrite) },
	{ 0x8dc7f424, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "65F40B5343F32F11D193ED5");
