#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{        0, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0x32f19e0, __VMLINUX_SYMBOL_STR(scsi_set_medium_removal) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xb5012304, __VMLINUX_SYMBOL_STR(blk_queue_rq_timeout) },
	{ 0x985a9beb, __VMLINUX_SYMBOL_STR(scsi_prep_return) },
	{ 0xf9a482f9, __VMLINUX_SYMBOL_STR(msleep) },
	{ 0x4b719758, __VMLINUX_SYMBOL_STR(alloc_disk) },
	{ 0xa21c7908, __VMLINUX_SYMBOL_STR(blk_queue_io_opt) },
	{ 0x4ae04c08, __VMLINUX_SYMBOL_STR(blk_queue_prep_rq) },
	{ 0xfbb97624, __VMLINUX_SYMBOL_STR(blk_add_request_payload) },
	{ 0x20eadeb6, __VMLINUX_SYMBOL_STR(ip_compute_csum) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0xc8c9e99, __VMLINUX_SYMBOL_STR(scsi_show_extd_sense) },
	{ 0x3a9b6fb9, __VMLINUX_SYMBOL_STR(blk_unregister_region) },
	{ 0x1c6f0368, __VMLINUX_SYMBOL_STR(dev_set_drvdata) },
	{ 0x28c17900, __VMLINUX_SYMBOL_STR(dev_printk) },
	{ 0x60c3277, __VMLINUX_SYMBOL_STR(scsi_execute_req_flags) },
	{ 0x20000329, __VMLINUX_SYMBOL_STR(simple_strtoul) },
	{ 0x3575a173, __VMLINUX_SYMBOL_STR(blk_queue_io_min) },
	{ 0xefba93e1, __VMLINUX_SYMBOL_STR(mempool_destroy) },
	{ 0x63b84a98, __VMLINUX_SYMBOL_STR(scsi_print_sense) },
	{ 0xef50fca9, __VMLINUX_SYMBOL_STR(scsi_mode_select) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x5087c92a, __VMLINUX_SYMBOL_STR(blk_queue_flush) },
	{ 0x6bd10e20, __VMLINUX_SYMBOL_STR(blk_queue_alignment_offset) },
	{ 0x304e69d1, __VMLINUX_SYMBOL_STR(revalidate_disk) },
	{ 0x5635853d, __VMLINUX_SYMBOL_STR(scsi_cmd_blk_ioctl) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0xf2933e75, __VMLINUX_SYMBOL_STR(scsi_autopm_get_device) },
	{ 0x6d3a1159, __VMLINUX_SYMBOL_STR(scsi_setup_fs_cmnd) },
	{ 0x183fa88b, __VMLINUX_SYMBOL_STR(mempool_alloc_slab) },
	{ 0x60ea2d6, __VMLINUX_SYMBOL_STR(kstrtoull) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xb6c5a973, __VMLINUX_SYMBOL_STR(scsi_show_result) },
	{ 0xfad5c7a1, __VMLINUX_SYMBOL_STR(device_del) },
	{ 0x1065bcd, __VMLINUX_SYMBOL_STR(check_disk_change) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x720442f4, __VMLINUX_SYMBOL_STR(del_gendisk) },
	{ 0x7ad5d5b5, __VMLINUX_SYMBOL_STR(class_unregister) },
	{ 0xaf3dd7dc, __VMLINUX_SYMBOL_STR(scsi_logging_level) },
	{ 0xc13b1fc5, __VMLINUX_SYMBOL_STR(blk_queue_unprep_rq) },
	{ 0xd477d6e2, __VMLINUX_SYMBOL_STR(driver_unregister) },
	{ 0xcf0a899c, __VMLINUX_SYMBOL_STR(blk_register_region) },
	{ 0xd4d67640, __VMLINUX_SYMBOL_STR(scsi_report_opcode) },
	{ 0x5a921311, __VMLINUX_SYMBOL_STR(strncmp) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x71a50dbc, __VMLINUX_SYMBOL_STR(register_blkdev) },
	{ 0x8a99a016, __VMLINUX_SYMBOL_STR(mempool_free_slab) },
	{ 0x3c9d1211, __VMLINUX_SYMBOL_STR(string_get_size) },
	{ 0x95bb7165, __VMLINUX_SYMBOL_STR(device_add) },
	{ 0xc34ba211, __VMLINUX_SYMBOL_STR(__class_register) },
	{ 0xd951f265, __VMLINUX_SYMBOL_STR(scsi_prep_fn) },
	{ 0x5d550c4d, __VMLINUX_SYMBOL_STR(scsi_sd_probe_domain) },
	{ 0xb5a459dc, __VMLINUX_SYMBOL_STR(unregister_blkdev) },
	{ 0x52aacc0e, __VMLINUX_SYMBOL_STR(scsi_device_put) },
	{ 0xb1c0c1c2, __VMLINUX_SYMBOL_STR(async_schedule_domain) },
	{ 0x2d89342a, __VMLINUX_SYMBOL_STR(scsi_show_sense_hdr) },
	{ 0xc6cbbc89, __VMLINUX_SYMBOL_STR(capable) },
	{ 0xea248cef, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0xe9dff136, __VMLINUX_SYMBOL_STR(mempool_alloc) },
	{ 0x4aff7de5, __VMLINUX_SYMBOL_STR(put_device) },
	{ 0x3a725ec4, __VMLINUX_SYMBOL_STR(blk_queue_physical_block_size) },
	{ 0xdf8f0bee, __VMLINUX_SYMBOL_STR(scsi_verify_blk_ioctl) },
	{ 0x2fc829d, __VMLINUX_SYMBOL_STR(scsi_nonblockable_ioctl) },
	{ 0x8200b8c3, __VMLINUX_SYMBOL_STR(scsi_ioctl) },
	{ 0xba0dccd0, __VMLINUX_SYMBOL_STR(put_disk) },
	{ 0x3f71faa1, __VMLINUX_SYMBOL_STR(mempool_create) },
	{ 0xf15b0d71, __VMLINUX_SYMBOL_STR(scsi_register_driver) },
	{ 0x6755e7dd, __VMLINUX_SYMBOL_STR(scsi_block_when_processing_errors) },
	{ 0x2629b7f6, __VMLINUX_SYMBOL_STR(scsi_test_unit_ready) },
	{ 0x52535c4, __VMLINUX_SYMBOL_STR(scsi_device_set_state) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x4aad52d7, __VMLINUX_SYMBOL_STR(mempool_free) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xc50cddc1, __VMLINUX_SYMBOL_STR(scsi_command_normalize_sense) },
	{ 0x4994dbfa, __VMLINUX_SYMBOL_STR(get_device) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0xdada4e3a, __VMLINUX_SYMBOL_STR(scsicam_bios_param) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x248c273b, __VMLINUX_SYMBOL_STR(ida_remove) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x6ca4bf88, __VMLINUX_SYMBOL_STR(async_synchronize_full_domain) },
	{ 0xa46f2f1b, __VMLINUX_SYMBOL_STR(kstrtouint) },
	{ 0xade5819a, __VMLINUX_SYMBOL_STR(add_disk) },
	{ 0x5182420f, __VMLINUX_SYMBOL_STR(ida_pre_get) },
	{ 0xca4e992c, __VMLINUX_SYMBOL_STR(device_initialize) },
	{ 0x270768ff, __VMLINUX_SYMBOL_STR(scsi_get_vpd_page) },
	{ 0x796fc5ce, __VMLINUX_SYMBOL_STR(scsi_get_sense_info_fld) },
	{ 0xa8721b97, __VMLINUX_SYMBOL_STR(system_state) },
	{ 0xb7335060, __VMLINUX_SYMBOL_STR(scsi_print_result) },
	{ 0x9ba4a9cc, __VMLINUX_SYMBOL_STR(blk_pm_runtime_init) },
	{ 0x1a091202, __VMLINUX_SYMBOL_STR(scsi_setup_blk_pc_cmnd) },
	{ 0xc666a132, __VMLINUX_SYMBOL_STR(crc_t10dif) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xb0e602eb, __VMLINUX_SYMBOL_STR(memmove) },
	{ 0xbaaea7eb, __VMLINUX_SYMBOL_STR(dev_set_name) },
	{ 0xa41e9598, __VMLINUX_SYMBOL_STR(scsi_device_get) },
	{ 0x7ff2d1f1, __VMLINUX_SYMBOL_STR(scsi_autopm_put_device) },
	{ 0x3ea0773c, __VMLINUX_SYMBOL_STR(ida_get_new_above) },
	{ 0xd3cf9783, __VMLINUX_SYMBOL_STR(blk_queue_logical_block_size) },
	{ 0xc1138708, __VMLINUX_SYMBOL_STR(dev_get_drvdata) },
	{ 0x5398fb3c, __VMLINUX_SYMBOL_STR(scsi_mode_sense) },
	{ 0xc7af3b3a, __VMLINUX_SYMBOL_STR(blk_queue_max_write_same_sectors) },
	{ 0x172f557, __VMLINUX_SYMBOL_STR(blk_integrity_register) },
	{ 0xb31e52e0, __VMLINUX_SYMBOL_STR(set_disk_ro) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=crc-t10dif";


MODULE_INFO(srcversion, "9C301EE7E0D4642229685C3");
