#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf3017e21, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x49045426, __VMLINUX_SYMBOL_STR(icmp_err_convert) },
	{ 0x1da47a60, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0xd41091d1, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0x926db1ea, __VMLINUX_SYMBOL_STR(ip_getsockopt) },
	{ 0x4fd4b719, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x61d6f07d, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xa12faeb0, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x8497c607, __VMLINUX_SYMBOL_STR(ip_setsockopt) },
	{ 0xf6b5267d, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0x1253ee82, __VMLINUX_SYMBOL_STR(ip_build_and_send_pkt) },
	{ 0xfcaabb81, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x6d8a6160, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x2ab8c8c4, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xc53049e4, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0xdbd6dcfb, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0x7ee58424, __VMLINUX_SYMBOL_STR(dccp_send_sync) },
	{ 0xe7531f86, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0xd78e6f89, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0xc9b7252a, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x9222d35, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0x5cea51c8, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xd148b433, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0x7d6f7c2f, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0xaf251786, __VMLINUX_SYMBOL_STR(inet_del_protocol) },
	{ 0xdfd4df42, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x7d11c268, __VMLINUX_SYMBOL_STR(jiffies) },
	{ 0x302bf08d, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xa68eee14, __VMLINUX_SYMBOL_STR(compat_sock_common_setsockopt) },
	{ 0xb2f5c9a4, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xf5b1c7a4, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0xdd557cf0, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x6374bed6, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xc28ffb0e, __VMLINUX_SYMBOL_STR(__pskb_pull_tail) },
	{ 0xd1ae1d3b, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x4313282e, __VMLINUX_SYMBOL_STR(compat_sock_common_getsockopt) },
	{ 0x13ceaf6f, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xf7a0ed77, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x507b2113, __VMLINUX_SYMBOL_STR(compat_ip_getsockopt) },
	{ 0x9fc4d620, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0x220821d8, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xf2d6c6e8, __VMLINUX_SYMBOL_STR(compat_dccp_setsockopt) },
	{ 0xe3fed51a, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x525adb77, __VMLINUX_SYMBOL_STR(inet_csk_update_pmtu) },
	{ 0x2deda4a1, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0xe5a3111b, __VMLINUX_SYMBOL_STR(inet_csk_route_req) },
	{ 0xf94ecc6e, __VMLINUX_SYMBOL_STR(inet_csk_search_req) },
	{ 0x4da2ab58, __VMLINUX_SYMBOL_STR(inet_csk_delete_keepalive_timer) },
	{ 0x25913c5, __VMLINUX_SYMBOL_STR(inet_csk_route_child_sock) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x7ae94dc0, __VMLINUX_SYMBOL_STR(inet_hash_connect) },
	{ 0x13a1a61a, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x1ee635a9, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x1b1ba32, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0x8db22c9c, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x34ab1d4c, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0x42fd6b21, __VMLINUX_SYMBOL_STR(inet_add_protocol) },
	{ 0xe3691b9d, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0xb902e8aa, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xa20ce1b8, __VMLINUX_SYMBOL_STR(net_msg_warn) },
	{ 0x7755f67c, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x5118c382, __VMLINUX_SYMBOL_STR(secure_dccp_sequence_number) },
	{ 0x2f75c37f, __VMLINUX_SYMBOL_STR(inet_ioctl) },
	{ 0x8b796fb5, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0xfcd20aa, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x3b4f903f, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x6c371985, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x66863997, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0xbd790825, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x9427f17a, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x7c0869db, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0xa7df5fec, __VMLINUX_SYMBOL_STR(inet_release) },
	{ 0xd374512c, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0x1e30711d, __VMLINUX_SYMBOL_STR(__ip_route_output_key) },
	{ 0xb993513, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0xd75ecda, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xc4b6d353, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x6ed2dd2b, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x37eb9b16, __VMLINUX_SYMBOL_STR(inet_getname) },
	{ 0x50d24064, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0x18157792, __VMLINUX_SYMBOL_STR(inet_csk_bind_conflict) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x1cc56456, __VMLINUX_SYMBOL_STR(__inet_hash_nolisten) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0x5bf3ebe1, __VMLINUX_SYMBOL_STR(compat_ip_setsockopt) },
	{ 0xe93d9ce7, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0x14e5e100, __VMLINUX_SYMBOL_STR(inet_csk_reqsk_queue_hash_add) },
	{ 0x2a18c74, __VMLINUX_SYMBOL_STR(nf_conntrack_destroy) },
	{ 0xdbcc1f73, __VMLINUX_SYMBOL_STR(compat_dccp_getsockopt) },
	{ 0x32476389, __VMLINUX_SYMBOL_STR(ip_route_output_flow) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xeabdcf2c, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0x3ffd5bea, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0x996a18f1, __VMLINUX_SYMBOL_STR(inet_register_protosw) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x649e5e77, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0xab748e16, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0xabddb475, __VMLINUX_SYMBOL_STR(inet_bind) },
	{ 0x78cfc7d4, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0x86be7924, __VMLINUX_SYMBOL_STR(dccp_packet_name) },
	{ 0x7824e86c, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0x3472474b, __VMLINUX_SYMBOL_STR(__inet_lookup_listener) },
	{ 0x5fcb0eb6, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x769cec0, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0xb6e80fea, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x9491e941, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0xab97a9a9, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x737ec71, __VMLINUX_SYMBOL_STR(inet_unregister_protosw) },
	{ 0x588a8096, __VMLINUX_SYMBOL_STR(inet_csk_addr2sockaddr) },
	{ 0x19b2947f, __VMLINUX_SYMBOL_STR(__inet_lookup_established) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp";


MODULE_INFO(srcversion, "79034AE8FFA88B79C657318");
