#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xf3017e21, __VMLINUX_SYMBOL_STR(dccp_statistics) },
	{ 0x1da47a60, __VMLINUX_SYMBOL_STR(dccp_init_sock) },
	{ 0x8161299b, __VMLINUX_SYMBOL_STR(__kfree_skb) },
	{ 0x718a90cf, __VMLINUX_SYMBOL_STR(dccp_v4_do_rcv) },
	{ 0xe4615063, __VMLINUX_SYMBOL_STR(inet6_csk_update_pmtu) },
	{ 0xd0e60ccd, __VMLINUX_SYMBOL_STR(sk_filter) },
	{ 0xd41091d1, __VMLINUX_SYMBOL_STR(dccp_set_state) },
	{ 0xecf49e5e, __VMLINUX_SYMBOL_STR(inet6_csk_bind_conflict) },
	{ 0xf13bdb17, __VMLINUX_SYMBOL_STR(ipv6_getsockopt) },
	{ 0x4fd4b719, __VMLINUX_SYMBOL_STR(inet_unhash) },
	{ 0x61d6f07d, __VMLINUX_SYMBOL_STR(inet_twsk_put) },
	{ 0xa12faeb0, __VMLINUX_SYMBOL_STR(dccp_hashinfo) },
	{ 0x34654e15, __VMLINUX_SYMBOL_STR(inet6_add_protocol) },
	{ 0x22ea1346, __VMLINUX_SYMBOL_STR(inet6_lookup_listener) },
	{ 0xf6b5267d, __VMLINUX_SYMBOL_STR(dccp_sendmsg) },
	{ 0xf63d4622, __VMLINUX_SYMBOL_STR(ipv6_opt_accepted) },
	{ 0x5ef02d07, __VMLINUX_SYMBOL_STR(compat_ipv6_getsockopt) },
	{ 0xfcaabb81, __VMLINUX_SYMBOL_STR(sk_setup_caps) },
	{ 0x6d8a6160, __VMLINUX_SYMBOL_STR(dccp_ctl_make_reset) },
	{ 0x2ab8c8c4, __VMLINUX_SYMBOL_STR(dccp_destroy_sock) },
	{ 0xc53049e4, __VMLINUX_SYMBOL_STR(dccp_make_response) },
	{ 0xdbd6dcfb, __VMLINUX_SYMBOL_STR(dst_release) },
	{ 0xea11c617, __VMLINUX_SYMBOL_STR(skb_clone) },
	{ 0xe7531f86, __VMLINUX_SYMBOL_STR(dccp_rcv_established) },
	{ 0x3e82bac2, __VMLINUX_SYMBOL_STR(inet6_csk_search_req) },
	{ 0xd78e6f89, __VMLINUX_SYMBOL_STR(security_skb_classify_flow) },
	{ 0x3c4a9370, __VMLINUX_SYMBOL_STR(dccp_v4_conn_request) },
	{ 0xc9b7252a, __VMLINUX_SYMBOL_STR(inet_csk_prepare_forced_close) },
	{ 0x9222d35, __VMLINUX_SYMBOL_STR(dccp_create_openreq_child) },
	{ 0xf11abdec, __VMLINUX_SYMBOL_STR(ipv6_dup_options) },
	{ 0x5cea51c8, __VMLINUX_SYMBOL_STR(dccp_check_req) },
	{ 0xd148b433, __VMLINUX_SYMBOL_STR(inet_sendmsg) },
	{ 0xb581ae63, __VMLINUX_SYMBOL_STR(inet6_release) },
	{ 0xb0d888b, __VMLINUX_SYMBOL_STR(icmpv6_err_convert) },
	{ 0x9465f339, __VMLINUX_SYMBOL_STR(inet6_register_protosw) },
	{ 0x7d6f7c2f, __VMLINUX_SYMBOL_STR(dccp_recvmsg) },
	{ 0xe1458068, __VMLINUX_SYMBOL_STR(ip6_xmit) },
	{ 0xdfd4df42, __VMLINUX_SYMBOL_STR(inet_sk_rebuild_header) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x61ea6842, __VMLINUX_SYMBOL_STR(inet6_getname) },
	{ 0x32c86cf5, __VMLINUX_SYMBOL_STR(sock_rfree) },
	{ 0x5d989405, __VMLINUX_SYMBOL_STR(inet6_csk_xmit) },
	{ 0x90d98fad, __VMLINUX_SYMBOL_STR(__inet6_hash) },
	{ 0x302bf08d, __VMLINUX_SYMBOL_STR(dccp_ioctl) },
	{ 0xa68eee14, __VMLINUX_SYMBOL_STR(compat_sock_common_setsockopt) },
	{ 0xb2f5c9a4, __VMLINUX_SYMBOL_STR(dccp_setsockopt) },
	{ 0xf5b1c7a4, __VMLINUX_SYMBOL_STR(sock_common_recvmsg) },
	{ 0x27c33efe, __VMLINUX_SYMBOL_STR(csum_ipv6_magic) },
	{ 0xdd557cf0, __VMLINUX_SYMBOL_STR(sock_no_sendpage) },
	{ 0x6374bed6, __VMLINUX_SYMBOL_STR(dccp_child_process) },
	{ 0xd1ae1d3b, __VMLINUX_SYMBOL_STR(sock_no_mmap) },
	{ 0x4313282e, __VMLINUX_SYMBOL_STR(compat_sock_common_getsockopt) },
	{ 0x13ceaf6f, __VMLINUX_SYMBOL_STR(sock_no_socketpair) },
	{ 0xf7a0ed77, __VMLINUX_SYMBOL_STR(skb_checksum) },
	{ 0x3f71b38d, __VMLINUX_SYMBOL_STR(ip6_dst_lookup_flow) },
	{ 0x9fc4d620, __VMLINUX_SYMBOL_STR(unregister_pernet_subsys) },
	{ 0xba1ee9df, __VMLINUX_SYMBOL_STR(__inet6_lookup_established) },
	{ 0xbff236da, __VMLINUX_SYMBOL_STR(dccp_v4_request_recv_sock) },
	{ 0x220821d8, __VMLINUX_SYMBOL_STR(dccp_parse_options) },
	{ 0xf2d6c6e8, __VMLINUX_SYMBOL_STR(compat_dccp_setsockopt) },
	{ 0xe3fed51a, __VMLINUX_SYMBOL_STR(dccp_getsockopt) },
	{ 0x9c3c34c, __VMLINUX_SYMBOL_STR(inet6_csk_reqsk_queue_hash_add) },
	{ 0x2deda4a1, __VMLINUX_SYMBOL_STR(security_sk_classify_flow) },
	{ 0x96a65460, __VMLINUX_SYMBOL_STR(inet6_ioctl) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x3c3fce39, __VMLINUX_SYMBOL_STR(__local_bh_enable_ip) },
	{ 0x4da2ab58, __VMLINUX_SYMBOL_STR(inet_csk_delete_keepalive_timer) },
	{ 0xe85fe49a, __VMLINUX_SYMBOL_STR(fl6_sock_lookup) },
	{ 0xd8525ea7, __VMLINUX_SYMBOL_STR(fl6_update_dst) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0x13a1a61a, __VMLINUX_SYMBOL_STR(_raw_write_lock) },
	{ 0x1ee635a9, __VMLINUX_SYMBOL_STR(dccp_reqsk_init) },
	{ 0x1b1ba32, __VMLINUX_SYMBOL_STR(dccp_close) },
	{ 0x8db22c9c, __VMLINUX_SYMBOL_STR(sk_free) },
	{ 0x34ab1d4c, __VMLINUX_SYMBOL_STR(inet_shutdown) },
	{ 0xe3691b9d, __VMLINUX_SYMBOL_STR(dccp_orphan_count) },
	{ 0xb902e8aa, __VMLINUX_SYMBOL_STR(dccp_sync_mss) },
	{ 0xa20ce1b8, __VMLINUX_SYMBOL_STR(net_msg_warn) },
	{ 0x42fce310, __VMLINUX_SYMBOL_STR(inet6_hash_connect) },
	{ 0x7755f67c, __VMLINUX_SYMBOL_STR(inet_accept) },
	{ 0x8b796fb5, __VMLINUX_SYMBOL_STR(inet_csk_get_port) },
	{ 0xfcd20aa, __VMLINUX_SYMBOL_STR(dccp_death_row) },
	{ 0x3b4f903f, __VMLINUX_SYMBOL_STR(inet_ctl_sock_create) },
	{ 0x6c371985, __VMLINUX_SYMBOL_STR(dccp_poll) },
	{ 0x66863997, __VMLINUX_SYMBOL_STR(inet_hash) },
	{ 0xbd790825, __VMLINUX_SYMBOL_STR(proto_register) },
	{ 0x9427f17a, __VMLINUX_SYMBOL_STR(dccp_disconnect) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0x7c0869db, __VMLINUX_SYMBOL_STR(__sk_dst_check) },
	{ 0xd374512c, __VMLINUX_SYMBOL_STR(dccp_done) },
	{ 0xb993513, __VMLINUX_SYMBOL_STR(sk_release_kernel) },
	{ 0x3870bf84, __VMLINUX_SYMBOL_STR(dccp_v4_send_check) },
	{ 0xd75ecda, __VMLINUX_SYMBOL_STR(kfree_skb) },
	{ 0xc4b6d353, __VMLINUX_SYMBOL_STR(proto_unregister) },
	{ 0x6ed2dd2b, __VMLINUX_SYMBOL_STR(inet_stream_connect) },
	{ 0x5cc0e64a, __VMLINUX_SYMBOL_STR(dccp_invalid_packet) },
	{ 0x54cc1e5b, __VMLINUX_SYMBOL_STR(inet6_del_protocol) },
	{ 0x50d24064, __VMLINUX_SYMBOL_STR(register_pernet_subsys) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x9f9f48f6, __VMLINUX_SYMBOL_STR(inet6_lookup) },
	{ 0x4cdd391d, __VMLINUX_SYMBOL_STR(dccp_feat_list_purge) },
	{ 0xb8817c40, __VMLINUX_SYMBOL_STR(dccp_syn_ack_timeout) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xe93d9ce7, __VMLINUX_SYMBOL_STR(sk_receive_skb) },
	{ 0xdbcc1f73, __VMLINUX_SYMBOL_STR(compat_dccp_getsockopt) },
	{ 0x5843a68, __VMLINUX_SYMBOL_STR(ipv6_setsockopt) },
	{ 0xf6ebc03b, __VMLINUX_SYMBOL_STR(net_ratelimit) },
	{ 0xeabdcf2c, __VMLINUX_SYMBOL_STR(sock_common_setsockopt) },
	{ 0xc772be5, __VMLINUX_SYMBOL_STR(inet6_sk_rebuild_header) },
	{ 0x3ffd5bea, __VMLINUX_SYMBOL_STR(__xfrm_policy_check) },
	{ 0xae729e59, __VMLINUX_SYMBOL_STR(security_req_classify_flow) },
	{ 0xe1761617, __VMLINUX_SYMBOL_STR(security_inet_conn_request) },
	{ 0x649e5e77, __VMLINUX_SYMBOL_STR(inet_dccp_listen) },
	{ 0xab748e16, __VMLINUX_SYMBOL_STR(__inet_inherit_port) },
	{ 0x78cfc7d4, __VMLINUX_SYMBOL_STR(sock_common_getsockopt) },
	{ 0xe200f872, __VMLINUX_SYMBOL_STR(secure_dccpv6_sequence_number) },
	{ 0xe38685ca, __VMLINUX_SYMBOL_STR(inet6_unregister_protosw) },
	{ 0x7824e86c, __VMLINUX_SYMBOL_STR(inet_csk_accept) },
	{ 0xa571ea44, __VMLINUX_SYMBOL_STR(inet6_bind) },
	{ 0x5fcb0eb6, __VMLINUX_SYMBOL_STR(dccp_reqsk_send_ack) },
	{ 0x769cec0, __VMLINUX_SYMBOL_STR(dccp_rcv_state_process) },
	{ 0x30e90d20, __VMLINUX_SYMBOL_STR(consume_skb) },
	{ 0xb6e80fea, __VMLINUX_SYMBOL_STR(dccp_connect) },
	{ 0x9491e941, __VMLINUX_SYMBOL_STR(dccp_shutdown) },
	{ 0xab97a9a9, __VMLINUX_SYMBOL_STR(ip_queue_xmit) },
	{ 0x2ff53b16, __VMLINUX_SYMBOL_STR(dccp_v4_connect) },
	{ 0xd542439, __VMLINUX_SYMBOL_STR(__ipv6_addr_type) },
	{ 0x798240bf, __VMLINUX_SYMBOL_STR(inet6_csk_addr2sockaddr) },
	{ 0x2a5c8c3b, __VMLINUX_SYMBOL_STR(compat_ipv6_setsockopt) },
	{ 0xe8def3f, __VMLINUX_SYMBOL_STR(inet6_destroy_sock) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=dccp,dccp_ipv4,ipv6";


MODULE_INFO(srcversion, "1A05B76851F13452C3BB6CE");
