part1:
	gcc barberShop-1.c -o p-1.out -std=c99 -pthread
	./p-1.out 3
part2:
	gcc barberShop-2.c -o p-2.out -std=c99 -pthread
	./p-2.out 3

debug:
	gcc barberShop.c -o p-1.out -std=c99 -pthread -g
	gdb ./p-1.out
