#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0xbe0247bf, __VMLINUX_SYMBOL_STR(vfs_create) },
	{ 0x770478e1, __VMLINUX_SYMBOL_STR(request_key) },
	{ 0x537143a2, __VMLINUX_SYMBOL_STR(kobject_put) },
	{        0, __VMLINUX_SYMBOL_STR(alloc_pages_current) },
	{ 0xa82ded68, __VMLINUX_SYMBOL_STR(kmem_cache_destroy) },
	{ 0xcda502fc, __VMLINUX_SYMBOL_STR(kernel_write) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0xd2b09ce5, __VMLINUX_SYMBOL_STR(__kmalloc) },
	{ 0x197b7dca, __VMLINUX_SYMBOL_STR(fsstack_copy_inode_size) },
	{ 0xc897c382, __VMLINUX_SYMBOL_STR(sg_init_table) },
	{ 0xaccca41, __VMLINUX_SYMBOL_STR(set_anon_super) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0x24de2513, __VMLINUX_SYMBOL_STR(make_bad_inode) },
	{ 0xbafbf0b1, __VMLINUX_SYMBOL_STR(generic_file_llseek) },
	{ 0xf2966369, __VMLINUX_SYMBOL_STR(__mark_inode_dirty) },
	{ 0xa518d865, __VMLINUX_SYMBOL_STR(mntget) },
	{ 0x3a53aea2, __VMLINUX_SYMBOL_STR(inode_permission) },
	{ 0xb6b46a7c, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x754d539c, __VMLINUX_SYMBOL_STR(strlen) },
	{ 0x60a13e90, __VMLINUX_SYMBOL_STR(rcu_barrier) },
	{ 0x3597bc07, __VMLINUX_SYMBOL_STR(iget5_locked) },
	{ 0x8841965b, __VMLINUX_SYMBOL_STR(kill_anon_super) },
	{ 0xcd78dec2, __VMLINUX_SYMBOL_STR(key_type_user) },
	{ 0xa2441376, __VMLINUX_SYMBOL_STR(dget_parent) },
	{ 0xa35a65ea, __VMLINUX_SYMBOL_STR(vfs_link) },
	{ 0x79aa04a2, __VMLINUX_SYMBOL_STR(get_random_bytes) },
	{ 0x7ab88a45, __VMLINUX_SYMBOL_STR(system_freezing_cnt) },
	{ 0xb1cf3c4e, __VMLINUX_SYMBOL_STR(__lock_page) },
	{ 0xdf2a91c0, __VMLINUX_SYMBOL_STR(filemap_write_and_wait) },
	{ 0x4ea05432, __VMLINUX_SYMBOL_STR(touch_atime) },
	{ 0xf608fa48, __VMLINUX_SYMBOL_STR(deactivate_locked_super) },
	{ 0x52cbb014, __VMLINUX_SYMBOL_STR(lockref_get) },
	{ 0x865e35da, __VMLINUX_SYMBOL_STR(generic_file_aio_read) },
	{ 0xa263917, __VMLINUX_SYMBOL_STR(dput) },
	{ 0xa05f372e, __VMLINUX_SYMBOL_STR(seq_printf) },
	{ 0x44e9a829, __VMLINUX_SYMBOL_STR(match_token) },
	{ 0x779b575f, __VMLINUX_SYMBOL_STR(dentry_open) },
	{ 0x3f2a0f29, __VMLINUX_SYMBOL_STR(init_user_ns) },
	{ 0x8b7fa33e, __VMLINUX_SYMBOL_STR(vfs_mknod) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0x85df9b6c, __VMLINUX_SYMBOL_STR(strsep) },
	{ 0xeb8c1100, __VMLINUX_SYMBOL_STR(vfs_fsync) },
	{ 0xd72edc5d, __VMLINUX_SYMBOL_STR(generic_read_dir) },
	{ 0x365d226, __VMLINUX_SYMBOL_STR(igrab) },
	{ 0x10724dd0, __VMLINUX_SYMBOL_STR(vfs_symlink) },
	{ 0x4629334c, __VMLINUX_SYMBOL_STR(__preempt_count) },
	{ 0x91715312, __VMLINUX_SYMBOL_STR(sprintf) },
	{ 0xe0ff5a4c, __VMLINUX_SYMBOL_STR(generic_file_aio_write) },
	{ 0x51b9a7be, __VMLINUX_SYMBOL_STR(sysfs_remove_group) },
	{ 0xb550b14e, __VMLINUX_SYMBOL_STR(kthread_create_on_node) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x6fda9a09, __VMLINUX_SYMBOL_STR(truncate_setsize) },
	{ 0xe2d5255a, __VMLINUX_SYMBOL_STR(strcmp) },
	{ 0xfad70f97, __VMLINUX_SYMBOL_STR(kobject_create_and_add) },
	{ 0x642fed8f, __VMLINUX_SYMBOL_STR(vfs_rmdir) },
	{ 0xc6fff74f, __VMLINUX_SYMBOL_STR(unlock_rename) },
	{ 0xf624038e, __VMLINUX_SYMBOL_STR(key_validate) },
	{ 0xf432dd3d, __VMLINUX_SYMBOL_STR(__init_waitqueue_head) },
	{ 0x6d0aba34, __VMLINUX_SYMBOL_STR(wait_for_completion) },
	{ 0x8ff73bbb, __VMLINUX_SYMBOL_STR(kernel_read) },
	{ 0x576b5a0e, __VMLINUX_SYMBOL_STR(kern_path) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0x572b72d8, __VMLINUX_SYMBOL_STR(crypto_alloc_ablkcipher) },
	{ 0xdaf23bd8, __VMLINUX_SYMBOL_STR(from_kuid) },
	{ 0xe5b2894f, __VMLINUX_SYMBOL_STR(default_llseek) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x17f02011, __VMLINUX_SYMBOL_STR(freezing_slow_path) },
	{ 0x5d9fa7a3, __VMLINUX_SYMBOL_STR(__mutex_init) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0xbfb3f5f4, __VMLINUX_SYMBOL_STR(kthread_stop) },
	{ 0xacee0f2e, __VMLINUX_SYMBOL_STR(d_rehash) },
	{ 0xab30892f, __VMLINUX_SYMBOL_STR(sysfs_create_group) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0xadaccc9, __VMLINUX_SYMBOL_STR(sget) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0x9166fada, __VMLINUX_SYMBOL_STR(strncpy) },
	{ 0xbf8ba54a, __VMLINUX_SYMBOL_STR(vprintk) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x1067195b, __VMLINUX_SYMBOL_STR(wait_on_sync_kiocb) },
	{ 0x139444fe, __VMLINUX_SYMBOL_STR(lock_rename) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0xad4edda, __VMLINUX_SYMBOL_STR(set_nlink) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0x154c8b30, __VMLINUX_SYMBOL_STR(unlock_page) },
	{ 0x3b4ceb4a, __VMLINUX_SYMBOL_STR(up_write) },
	{ 0xe6e3b875, __VMLINUX_SYMBOL_STR(down_write) },
	{ 0x9e44ca72, __VMLINUX_SYMBOL_STR(fput) },
	{ 0xcdf91efb, __VMLINUX_SYMBOL_STR(key_put) },
	{ 0xa4fc6e2a, __VMLINUX_SYMBOL_STR(inode_init_once) },
	{ 0x75a60ae8, __VMLINUX_SYMBOL_STR(atomic_dec_and_mutex_lock) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xea248cef, __VMLINUX_SYMBOL_STR(__free_pages) },
	{ 0x525912ad, __VMLINUX_SYMBOL_STR(generic_file_mmap) },
	{ 0x7a985d5f, __VMLINUX_SYMBOL_STR(fs_kobj) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{        0, __VMLINUX_SYMBOL_STR(do_sync_read) },
	{ 0xd5ddde83, __VMLINUX_SYMBOL_STR(unlock_new_inode) },
	{ 0x263ea25c, __VMLINUX_SYMBOL_STR(bdi_setup_and_register) },
	{ 0x556073d2, __VMLINUX_SYMBOL_STR(d_drop) },
	{ 0xd4b84b0e, __VMLINUX_SYMBOL_STR(inode_newsize_ok) },
	{ 0x4482cdb, __VMLINUX_SYMBOL_STR(__refrigerator) },
	{ 0x43b7c7de, __VMLINUX_SYMBOL_STR(crypto_destroy_tfm) },
	{ 0xdfa25c3f, __VMLINUX_SYMBOL_STR(vfs_mkdir) },
	{ 0x374e0d31, __VMLINUX_SYMBOL_STR(wake_up_process) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x933c234d, __VMLINUX_SYMBOL_STR(inode_change_ok) },
	{ 0xeff3f384, __VMLINUX_SYMBOL_STR(path_put) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0xaad21e16, __VMLINUX_SYMBOL_STR(vfs_unlink) },
	{ 0x24fcb3b4, __VMLINUX_SYMBOL_STR(kmem_cache_create) },
	{ 0xba797153, __VMLINUX_SYMBOL_STR(register_filesystem) },
	{ 0x96dc7e07, __VMLINUX_SYMBOL_STR(fsstack_copy_attr_all) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0xcf21d241, __VMLINUX_SYMBOL_STR(__wake_up) },
	{ 0xb3f7646e, __VMLINUX_SYMBOL_STR(kthread_should_stop) },
	{ 0x34f22f94, __VMLINUX_SYMBOL_STR(prepare_to_wait_event) },
	{ 0xb6244511, __VMLINUX_SYMBOL_STR(sg_init_one) },
	{ 0xd7317d, __VMLINUX_SYMBOL_STR(iput) },
	{ 0x6b0cbb7e, __VMLINUX_SYMBOL_STR(read_cache_page) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x861af486, __VMLINUX_SYMBOL_STR(do_sync_write) },
	{ 0x69acdf38, __VMLINUX_SYMBOL_STR(memcpy) },
	{ 0xa75312bc, __VMLINUX_SYMBOL_STR(call_rcu_sched) },
	{ 0x9e61bb05, __VMLINUX_SYMBOL_STR(set_freezable) },
	{ 0x6ebc5149, __VMLINUX_SYMBOL_STR(param_ops_long) },
	{ 0xbf955900, __VMLINUX_SYMBOL_STR(generic_readlink) },
	{ 0x312ca88d, __VMLINUX_SYMBOL_STR(put_page) },
	{ 0xbb79dce5, __VMLINUX_SYMBOL_STR(d_make_root) },
	{ 0x7a4497db, __VMLINUX_SYMBOL_STR(kzfree) },
	{ 0xfa66f77c, __VMLINUX_SYMBOL_STR(finish_wait) },
	{ 0x1f4fe7de, __VMLINUX_SYMBOL_STR(iterate_dir) },
	{ 0xfebd6590, __VMLINUX_SYMBOL_STR(bdi_destroy) },
	{ 0x7b22ce17, __VMLINUX_SYMBOL_STR(unregister_filesystem) },
	{ 0xbd5ebbe5, __VMLINUX_SYMBOL_STR(init_special_inode) },
	{ 0xb742fd7, __VMLINUX_SYMBOL_STR(simple_strtol) },
	{ 0x4b06d2e7, __VMLINUX_SYMBOL_STR(complete) },
	{ 0x28318305, __VMLINUX_SYMBOL_STR(snprintf) },
	{ 0xdcc6389d, __VMLINUX_SYMBOL_STR(kfree_put_link) },
	{ 0xd2c50e95, __VMLINUX_SYMBOL_STR(generic_file_splice_read) },
	{ 0xc6613614, __VMLINUX_SYMBOL_STR(lookup_one_len) },
	{ 0x920ec4cb, __VMLINUX_SYMBOL_STR(vfs_rename) },
	{ 0xcfb919c1, __VMLINUX_SYMBOL_STR(vfs_getattr) },
	{ 0x4019851b, __VMLINUX_SYMBOL_STR(crypto_alloc_base) },
	{ 0x267ef61f, __VMLINUX_SYMBOL_STR(grab_cache_page_write_begin) },
	{ 0x47c8baf4, __VMLINUX_SYMBOL_STR(param_ops_uint) },
	{ 0x47e25d17, __VMLINUX_SYMBOL_STR(notify_change) },
	{ 0xf2ed33b1, __VMLINUX_SYMBOL_STR(vfs_setxattr) },
	{ 0x1bac5398, __VMLINUX_SYMBOL_STR(clear_inode) },
	{ 0x1a7ce1b9, __VMLINUX_SYMBOL_STR(d_instantiate) },
	{ 0x6f2bc228, __VMLINUX_SYMBOL_STR(clear_nlink) },
	{ 0x4c1b0f4e, __VMLINUX_SYMBOL_STR(generic_fillattr) },
	{ 0xe914e41e, __VMLINUX_SYMBOL_STR(strcpy) },
	{ 0x8dc7f424, __VMLINUX_SYMBOL_STR(truncate_inode_pages) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=";


MODULE_INFO(srcversion, "AEB4BEABD40AFADFB04BA82");
