#include <linux/module.h>
#include <linux/vermagic.h>
#include <linux/compiler.h>

MODULE_INFO(vermagic, VERMAGIC_STRING);

__visible struct module __this_module
__attribute__((section(".gnu.linkonce.this_module"))) = {
	.name = KBUILD_MODNAME,
	.init = init_module,
#ifdef CONFIG_MODULE_UNLOAD
	.exit = cleanup_module,
#endif
	.arch = MODULE_ARCH_INIT,
};

MODULE_INFO(intree, "Y");

static const struct modversion_info ____versions[]
__used
__attribute__((section("__versions"))) = {
	{ 0x43804739, __VMLINUX_SYMBOL_STR(module_layout) },
	{ 0x87dc75e3, __VMLINUX_SYMBOL_STR(kvm_apic_write_nodecode) },
	{ 0xd0b2727a, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mask_ptes) },
	{ 0x44cedbf6, __VMLINUX_SYMBOL_STR(kmalloc_caches) },
	{ 0x65e75cb6, __VMLINUX_SYMBOL_STR(__list_del_entry) },
	{ 0xa1c4ecdb, __VMLINUX_SYMBOL_STR(kvm_complete_insn_gp) },
	{ 0x7991fd8d, __VMLINUX_SYMBOL_STR(crash_vmclear_loaded_vmcss) },
	{ 0x4c4fef19, __VMLINUX_SYMBOL_STR(kernel_stack) },
	{ 0xe5c404be, __VMLINUX_SYMBOL_STR(kvm_mmu_sync_roots) },
	{ 0xb0ef1b17, __VMLINUX_SYMBOL_STR(kvm_release_page_dirty) },
	{ 0x9498487a, __VMLINUX_SYMBOL_STR(kvm_inject_page_fault) },
	{ 0x64020e10, __VMLINUX_SYMBOL_STR(kvm_set_shared_msr) },
	{ 0x28e9276a, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit_inject) },
	{ 0xb6b46a7c, __VMLINUX_SYMBOL_STR(param_ops_int) },
	{ 0x39cf326d, __VMLINUX_SYMBOL_STR(kvm_set_msr_common) },
	{ 0x5c97cb51, __VMLINUX_SYMBOL_STR(kvm_mmu_invlpg) },
	{ 0xd13b9598, __VMLINUX_SYMBOL_STR(kvm_inject_realmode_interrupt) },
	{ 0x738f07f8, __VMLINUX_SYMBOL_STR(handle_mmio_page_fault_common) },
	{ 0x177fbefc, __VMLINUX_SYMBOL_STR(kvm_vcpu_kick) },
	{ 0xc45e789c, __VMLINUX_SYMBOL_STR(kvm_vcpu_init) },
	{ 0xfbb5e1e6, __VMLINUX_SYMBOL_STR(node_data) },
	{ 0x566eb4d, __VMLINUX_SYMBOL_STR(kvm_apic_set_eoi_accelerated) },
	{ 0xc715d9e0, __VMLINUX_SYMBOL_STR(boot_cpu_data) },
	{ 0x4388cd5a, __VMLINUX_SYMBOL_STR(kvm_emulate_cpuid) },
	{ 0x48cb45af, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_exit) },
	{ 0x12a34a9b, __VMLINUX_SYMBOL_STR(kvm_queue_exception_e) },
	{ 0x8fd989f3, __VMLINUX_SYMBOL_STR(kvm_get_rflags) },
	{ 0xeb59e8c3, __VMLINUX_SYMBOL_STR(native_load_gs_index) },
	{ 0x485cd7f6, __VMLINUX_SYMBOL_STR(kvm_rebooting) },
	{ 0x7c309fa6, __VMLINUX_SYMBOL_STR(__srcu_read_unlock) },
	{ 0x4a01bee0, __VMLINUX_SYMBOL_STR(kvm_read_guest) },
	{ 0xc0a3d105, __VMLINUX_SYMBOL_STR(find_next_bit) },
	{ 0xca689036, __VMLINUX_SYMBOL_STR(kvm_vcpu_on_spin) },
	{ 0xb494ce41, __VMLINUX_SYMBOL_STR(kvm_mmu_unload) },
	{ 0xc87c1f84, __VMLINUX_SYMBOL_STR(ktime_get) },
	{ 0xf087137d, __VMLINUX_SYMBOL_STR(__dynamic_pr_debug) },
	{ 0x65699fef, __VMLINUX_SYMBOL_STR(kvm_mmu_reset_context) },
	{ 0x33ba5cd4, __VMLINUX_SYMBOL_STR(param_ops_bool) },
	{ 0x79c59ec3, __VMLINUX_SYMBOL_STR(mutex_unlock) },
	{ 0xbe15d5c8, __VMLINUX_SYMBOL_STR(kvm_mmu_page_fault) },
	{ 0x44aaf30f, __VMLINUX_SYMBOL_STR(tsc_khz) },
	{ 0x54efb5d6, __VMLINUX_SYMBOL_STR(cpu_number) },
	{ 0x96a61278, __VMLINUX_SYMBOL_STR(kvm_get_dr) },
	{ 0x8001c4b0, __VMLINUX_SYMBOL_STR(kvm_set_cr8) },
	{ 0xf54bf722, __VMLINUX_SYMBOL_STR(__alloc_pages_nodemask) },
	{ 0xd3a88ca1, __VMLINUX_SYMBOL_STR(kvm_set_cr0) },
	{ 0x343a1a8, __VMLINUX_SYMBOL_STR(__list_add) },
	{ 0x2451baac, __VMLINUX_SYMBOL_STR(kvm_release_page_clean) },
	{ 0x17c4ab89, __VMLINUX_SYMBOL_STR(kvm_set_cr4) },
	{ 0xfe7c4287, __VMLINUX_SYMBOL_STR(nr_cpu_ids) },
	{ 0xab38bdb7, __VMLINUX_SYMBOL_STR(kvm_get_guest_memory_type) },
	{ 0xfb578fc5, __VMLINUX_SYMBOL_STR(memset) },
	{ 0xc4f51bb5, __VMLINUX_SYMBOL_STR(kvm_mmu_unprotect_page_virt) },
	{ 0x8cbbb980, __VMLINUX_SYMBOL_STR(kvm_write_tsc) },
	{ 0x260617f2, __VMLINUX_SYMBOL_STR(current_task) },
	{ 0x27e1a049, __VMLINUX_SYMBOL_STR(printk) },
	{ 0x29444f0, __VMLINUX_SYMBOL_STR(native_read_tsc) },
	{ 0x709cd8cb, __VMLINUX_SYMBOL_STR(kvm_spurious_fault) },
	{ 0x449ad0a7, __VMLINUX_SYMBOL_STR(memcmp) },
	{ 0x7ac80dd8, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_msr) },
	{ 0x4c9d28b0, __VMLINUX_SYMBOL_STR(phys_base) },
	{ 0x330ec749, __VMLINUX_SYMBOL_STR(kvm_emulate_hypercall) },
	{ 0xc83163f0, __VMLINUX_SYMBOL_STR(kvm_set_dr) },
	{ 0xc8d0007, __VMLINUX_SYMBOL_STR(kvm_vcpu_cache) },
	{ 0xa1c76e0a, __VMLINUX_SYMBOL_STR(_cond_resched) },
	{ 0xd5e348b5, __VMLINUX_SYMBOL_STR(kvm_x86_ops) },
	{ 0xa7b5a08f, __VMLINUX_SYMBOL_STR(kvm_get_cr8) },
	{ 0xd6d36ae7, __VMLINUX_SYMBOL_STR(kmem_cache_free) },
	{ 0x16305289, __VMLINUX_SYMBOL_STR(warn_slowpath_null) },
	{ 0xe1504556, __VMLINUX_SYMBOL_STR(mutex_lock) },
	{ 0x808596ff, __VMLINUX_SYMBOL_STR(kvm_set_cr3) },
	{ 0x521445b, __VMLINUX_SYMBOL_STR(list_del) },
	{ 0xa8901bd3, __VMLINUX_SYMBOL_STR(kvm_emulate_wbinvd) },
	{ 0xc2cdbf1, __VMLINUX_SYMBOL_STR(synchronize_sched) },
	{ 0x846c0195, __VMLINUX_SYMBOL_STR(kvm_mmu_flush_tlb) },
	{ 0xdaa7d5a0, __VMLINUX_SYMBOL_STR(kvm_apic_update_irr) },
	{ 0xd96a2de6, __VMLINUX_SYMBOL_STR(__srcu_read_lock) },
	{ 0x4723db, __VMLINUX_SYMBOL_STR(kvm_before_handle_nmi) },
	{ 0xcca03002, __VMLINUX_SYMBOL_STR(cpu_bit_bitmap) },
	{ 0x82473dae, __VMLINUX_SYMBOL_STR(kvm_cpu_has_interrupt) },
	{ 0xb9352c30, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_inj_virq) },
	{ 0x6759a4fa, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_page_fault) },
	{ 0xf11543ff, __VMLINUX_SYMBOL_STR(find_first_zero_bit) },
	{ 0x38270269, __VMLINUX_SYMBOL_STR(kvm_valid_efer) },
	{ 0x4741a933, __VMLINUX_SYMBOL_STR(kmem_cache_alloc) },
	{ 0xc36d4585, __VMLINUX_SYMBOL_STR(kvm_write_guest_page) },
	{ 0x618911fc, __VMLINUX_SYMBOL_STR(numa_node) },
	{ 0xa2c9d375, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_write_tsc_offset) },
	{ 0x93fca811, __VMLINUX_SYMBOL_STR(__get_free_pages) },
	{ 0x243898fb, __VMLINUX_SYMBOL_STR(kvm_after_handle_nmi) },
	{ 0x5cff0053, __VMLINUX_SYMBOL_STR(kvm_queue_exception) },
	{ 0x73032782, __VMLINUX_SYMBOL_STR(cpu_possible_mask) },
	{ 0x1f5a7ff5, __VMLINUX_SYMBOL_STR(kvm_set_memory_region) },
	{ 0x1000e51, __VMLINUX_SYMBOL_STR(schedule) },
	{ 0x79a38e61, __VMLINUX_SYMBOL_STR(___ratelimit) },
	{ 0x6532aadd, __VMLINUX_SYMBOL_STR(kvm_lapic_set_eoi) },
	{ 0x53401406, __VMLINUX_SYMBOL_STR(kvm_lmsw) },
	{ 0x6b2dc060, __VMLINUX_SYMBOL_STR(dump_stack) },
	{ 0x46ac9ddc, __VMLINUX_SYMBOL_STR(kvm_requeue_exception_e) },
	{ 0x798b57cb, __VMLINUX_SYMBOL_STR(kvm_init_shadow_ept_mmu) },
	{ 0x64c8c32e, __VMLINUX_SYMBOL_STR(kvm_require_cpl) },
	{ 0xaaf935, __VMLINUX_SYMBOL_STR(kvm_disable_tdp) },
	{ 0xba9ed435, __VMLINUX_SYMBOL_STR(kvm_mmu_set_mmio_spte_mask) },
	{ 0x3bdd2c1e, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_cr) },
	{ 0xdd994393, __VMLINUX_SYMBOL_STR(x86_emulate_instruction) },
	{ 0xbdfb6dbb, __VMLINUX_SYMBOL_STR(__fentry__) },
	{ 0x99cee2e1, __VMLINUX_SYMBOL_STR(kvm_read_guest_virt) },
	{ 0x8ce4f3ab, __VMLINUX_SYMBOL_STR(kvm_enable_tdp) },
	{ 0xe82b3441, __VMLINUX_SYMBOL_STR(kvm_task_switch) },
	{ 0x2483197d, __VMLINUX_SYMBOL_STR(kvm_find_cpuid_entry) },
	{ 0x3bfce3c9, __VMLINUX_SYMBOL_STR(kmem_cache_alloc_trace) },
	{ 0x76df156b, __VMLINUX_SYMBOL_STR(kvm_write_guest_virt_system) },
	{ 0xd52bf1ce, __VMLINUX_SYMBOL_STR(_raw_spin_lock) },
	{ 0xb19a5453, __VMLINUX_SYMBOL_STR(__per_cpu_offset) },
	{ 0xdd744aa, __VMLINUX_SYMBOL_STR(kvm_set_xcr) },
	{ 0x9a216313, __VMLINUX_SYMBOL_STR(kvm_define_shared_msr) },
	{ 0x4302d0eb, __VMLINUX_SYMBOL_STR(free_pages) },
	{ 0x1e047854, __VMLINUX_SYMBOL_STR(warn_slowpath_fmt) },
	{ 0x58edc12, __VMLINUX_SYMBOL_STR(kvm_set_apic_base) },
	{ 0xdf988ed7, __VMLINUX_SYMBOL_STR(kvm_emulate_halt) },
	{ 0xdb90078b, __VMLINUX_SYMBOL_STR(kvm_arch_has_noncoherent_dma) },
	{ 0x7d8c163d, __VMLINUX_SYMBOL_STR(kvm_vcpu_uninit) },
	{ 0x37a0cba, __VMLINUX_SYMBOL_STR(kfree) },
	{ 0x140319c4, __VMLINUX_SYMBOL_STR(__kvm_set_memory_region) },
	{ 0x77242ab9, __VMLINUX_SYMBOL_STR(kvm_get_msr_common) },
	{ 0x6194ffea, __VMLINUX_SYMBOL_STR(do_machine_check) },
	{ 0x7628f3c7, __VMLINUX_SYMBOL_STR(this_cpu_off) },
	{ 0x4913af39, __VMLINUX_SYMBOL_STR(gfn_to_page) },
	{ 0x2073edb7, __VMLINUX_SYMBOL_STR(kvm_mmu_get_spte_hierarchy) },
	{ 0x4738f0ff, __VMLINUX_SYMBOL_STR(kvm_fast_pio_out) },
	{ 0x317f9e6b, __VMLINUX_SYMBOL_STR(kvm_enable_efer_bits) },
	{ 0xd255e300, __VMLINUX_SYMBOL_STR(apic) },
	{ 0xcdee36d6, __VMLINUX_SYMBOL_STR(__tracepoint_kvm_nested_vmexit) },
	{ 0x365e9e0c, __VMLINUX_SYMBOL_STR(kvm_set_msr) },
	{ 0x8dd2a284, __VMLINUX_SYMBOL_STR(kvm_init) },
	{ 0x27046576, __VMLINUX_SYMBOL_STR(kvm_exit) },
	{ 0x48682db9, __VMLINUX_SYMBOL_STR(perf_guest_get_msrs) },
	{ 0x20de5193, __VMLINUX_SYMBOL_STR(kvm_disable_largepages) },
	{ 0x54c149e8, __VMLINUX_SYMBOL_STR(kvm_requeue_exception) },
	{ 0x3ad1062, __VMLINUX_SYMBOL_STR(kvm_clear_guest_page) },
	{ 0x6228c21f, __VMLINUX_SYMBOL_STR(smp_call_function_single) },
	{ 0xdcb7fe91, __VMLINUX_SYMBOL_STR(kvm_rdpmc) },
};

static const char __module_depends[]
__used
__attribute__((section(".modinfo"))) =
"depends=kvm";

MODULE_ALIAS("x86cpu:vendor:*:family:*:model:*:feature:*0085*");

MODULE_INFO(srcversion, "C5724BC0CF244F1BE96DE30");
